spring:
  datasource:
    username: calculator
    password: calculator
    url: jdbc:postgresql://localhost:5436/congestion-calculator
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      #      Only to not use flyway/liquidbase
      continue-on-error: true